services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FRONTEND_URL=http://localhost:4173
    networks:
      - expense-splitter-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_SERVER_URL: http://localhost:3000/api
    ports:
      - "4173:4173"
    depends_on:
      - server
    networks:
      - expense-splitter-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - expense-splitter-network

volumes:
  pg_data:

networks:
  expense-splitter-network:
